Add probes to deployments
wisemen-digital/sysops-k8s-modules pull request #1
Opened 2024-06-15 14:22 UTC by jorenvandeweyer

Added liveness & readiness probes to the Nuxt deployment.

All Nuxt projects should add this in their repo. This is necessary since autorestart=false in the nuxt deamon.

```ts
// server/api/health.ts
export default defineEventHandler(() => 'OK')
```

2024-06-15 14:22 UTC, jorenvandeweyer commented
⚠️ deploying this might break existing nuxt deployments

2024-06-15 16:42 UTC, djbe requested changes
I don't think we need to talk to an `/api/health` endpoint. Just getting `/` is good enough for now.

Just tried running the (starline) image locally. When everything is fine:
```bash
$ curl -o - -I http://localhost:8080/
HTTP/1.1 302 Found
…
```

When I go in the container and kill the nuxt process:
```bash
$ curl -o - -I http://localhost:8080/
HTTP/1.1 502 Bad Gateway
…
```

2024-06-15 16:47 UTC, djbe commented
Note: I know a health probe is "better" if it can provide more info. But until we can guarantee that every nuxt project has a health endpoint that works, and maybe some others as well, we should make do with this. 

See for example the CMS Directus deployoment, tried using the endpoints they provide:
https://github.com/wisemen-digital/sysops-k8s-modules/blob/main/cms-directus/base/deployment.yaml#L43-L50

2024-06-16 19:04 UTC, jorenvandeweyer commented
> I don't think we need to talk to an `/api/health` endpoint. Just getting `/` is good enough for now.
> 
> Just tried running the (starline) image locally. When everything is fine:
> 
> ```shell
> $ curl -o - -I http://localhost:8080/
> HTTP/1.1 302 Found
> …
> ```
> 
> When I go in the container and kill the nuxt process:
> 
> ```shell
> $ curl -o - -I http://localhost:8080/
> HTTP/1.1 502 Bad Gateway
> …
> ```



I thought the 3xx code would not be sufficient for the health endpoint.

It seems I was wrong, the kubernetes docs state:
> Any code greater than or equal to 200 and less than 400 indicates success. Any other code indicates failure.

2024-06-16 19:54 UTC, djbe commented
Note: also think there isn't much of a point to override the initial delay & periods, they won't make a difference. In cases where you need an initial delay, you're probably better of configuring a startup probe instead.

2024-06-18 01:32 UTC, djbe commented
@jorenvandeweyer
- Can you confirm that `/api` always returns a success for node?
- Do all node projects happen to have a specific health endpoint?

@BertBijnens or @Michiel-Wisemen similar question for PHP.
- Is there a general endpoint that always returns a success (200)? Nothing fancy, no special response, just "ok". Essentially a `ping`.
- Health endpoint: I know [Laravel 11 has one](https://laravel-news.com/laravel-11-health-endpoint), but for older projects we could [use this](https://spatie.be/docs/laravel-health/v1/basic-usage/endpoints#content-simple-health-check) (the simple check).

2024-06-19 00:19 UTC, djbe approved these changes

2024-06-20 11:29 UTC, jorenvandeweyer commented
I can confirm this.

`/api` returns a 200 with the following body:
```ts
export interface ApiStatusType {
  environment?: string
  commit?: string
  version?: string // Github actions build number
}
```

2024-06-20 11:30 UTC, jorenvandeweyer reviewed
Changes look fine 👌

2024-06-20 22:32 UTC, djbe commented
Merging this for now, we'll wait a bit before adding this to PHP

2024-06-20 22:32 UTC, merged