PGbouncer - Initial commit
wisemen-digital/sysops-k8s-modules pull request #4
Opened 2024-08-29 15:53 UTC by daanpersoons-appwise

2024-08-29 19:23 UTC, djbe requested changes

2024-08-29 19:23 UTC, djbe commented on pgbouncer/base/deployment.yaml
> +                name: configmap-pgbouncer
Should we create a default config map? Not sure what goes in there that's the same in every project… They can always override it if needed 🤷

2024-08-29 19:23 UTC, djbe commented on pgbouncer/base/deployment.yaml
Will this be 1 pgbouncer instance for all environments (i.e. shared), or one for each env.? 'cause we may want to compare with the [setup there](https://github.com/edoburu/docker-pgbouncer/blob/master/examples/kubernetes/singleuser/deployment.yml).

2024-08-30 11:40 UTC, daanpersoons-appwise commented on pgbouncer/base/deployment.yaml
In old setups, it is 1 PGbouncer per environment, but if you want to I can try to set it up with a multiuser proxy.
It is not a bad idea because it will save a significant amount of resources on the cluster.

2024-08-30 11:54 UTC, daanpersoons-appwise commented on pgbouncer/base/deployment.yaml
Should it be Stateful? Maybe for the [stable network ID](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id) but I don't really see how it can benefit us.
It is nice that it will be in the same 'category' as redis and typesense, but I don't know if that is the correct way of approaching this

2024-08-30 12:00 UTC, daanpersoons-appwise commented on pgbouncer/base/deployment.yaml
> +                name: configmap-pgbouncer
For internal networking in k8s we could use the same username and password for all the environments in all projects. Easier to setup. The password configured from pgbouncer -> scaleway pg will still be unique.

2024-08-30 13:50 UTC, djbe commented on pgbouncer/base/deployment.yaml
It's more as an "indicator", for something that should remain online, be more careful with, etc… At least that's the impression I get from it. You can't "change" the service, it's supposed to point to the same pod(s), etc…

Note that it doesn't mean this thing needs an actual volume.

2024-08-30 13:51 UTC, djbe commented on pgbouncer/base/deployment.yaml
> +                name: configmap-pgbouncer
Honestly if we go the multiuser route, use the same user/pass for the bouncer as the DB itself. I think that's how DO does it?

If we go single user, same thing, but only one user :P

2024-08-30 13:52 UTC, djbe commented on pgbouncer/base/deployment.yaml
> +                name: configmap-pgbouncer
But no I didn't mean using the same user/pass in all projects. I meant this for settings that are probably the same in all projects, such as the mode, default pool sizes, etc…

2024-08-30 13:53 UTC, djbe commented on pgbouncer/base/deployment.yaml
> +                name: configmap-pgbouncer
The user/pass are loaded through a text file if I'm not mistaken.

2024-09-03 22:53 UTC, djbe requested changes
I've noticed you removed the `killall -INT pgbouncer && sleep 120`  shutdown thing. Did you check it's no longer needed? 

From this SO post we can invoke a command to shutdown pgbouncer gracefully:
https://stackoverflow.com/questions/75828221/how-to-safely-restart-postgresql-container-in-kubernetes
And official docs: https://www.postgresql.org/docs/current/server-shutdown.html

2024-09-03 22:53 UTC, djbe commented on pgbouncer/base/configmap.yaml
> +  DATABASE_URL: postgres://user:pass@postgres-host/database
I'm not sure I'd set the actual DB url here, we wanna make sure we set actual defaults we want to use.

If a setting, such as `DATABASE_URL` is missing wherever this is actually used, then that's GOOD, because it won't work, instead of trying to connect to non-existing databases.

2024-09-03 22:53 UTC, djbe commented on pgbouncer/base/configmap.yaml
> +  DATABASE_URL: postgres://user:pass@postgres-host/database
But yeah, as discussed on Slack, I'd add default settings such as connection type (transaction?), default pool sizes, certain maxima (connections, memory, …)

2024-09-03 22:53 UTC, djbe commented on pgbouncer/base/statefulset.yaml
> +              memory: 50M
Make that 64M

2024-09-03 22:53 UTC, djbe commented on pgbouncer/base/statefulset.yaml
> +              memory: 50M
Nitpick: move this after cpu, to keep them ordered 😉

2024-09-13 09:18 UTC, jorenvandeweyer requested changes

2024-09-13 09:18 UTC, jorenvandeweyer commented on pgbouncer/base/statefulset.yaml
statefulset verkeerd gebruikt hier 🤔

2024-09-13 16:11 UTC, daanpersoons-appwise commented on pgbouncer/base/statefulset.yaml
Herschreven naar deployment

2024-09-13 16:54 UTC, jorenvandeweyer approved these changes

2024-09-16 09:48 UTC, jorenvandeweyer approved these changes

2024-09-17 20:07 UTC, djbe approved these changes
Added `--wait` to killall, it was either that or adding a `sleep 120`. Hopefully this way it "can" stop earlier, with the sleep we'd always wait the full 120s

2024-09-17 20:07 UTC, merged